<a href="https://colab.research.google.com/github/amir-ab/Machine_Learning/blob/main/TreeDecision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("play_tennis.csv")

In [ ]:
df

outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   outlook   14 non-null     object
 1   temp      14 non-null     object
 2   humidity  14 non-null     object
 3   wind      14 non-null     object
 4   play      14 non-null     object
dtypes: object(5)
memory usage: 688.0+ bytes


In [ ]:
df.shape

(14, 5)

In [ ]:
df["play"]

0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: play, dtype: object

In [ ]:
df["play"][df["play"] == "No"].shape

(5,)

In [ ]:
df["play"][df["play"] == "Yes"].shape

(9,)

In [ ]:
df["play"].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
df["play"].nunique()

2

In [ ]:
E = - ( (5/14) * np.log2(5/14) + (9/14) * np.log2(9/14) )
E

0.9402859586706309

In [ ]:
# Comment calculer la table de contingence ( Cross Tab)
pd.crosstab( df["outlook"] , df["play"], margins=True);

In [ ]:
pd.crosstab( df["temp"] , df["play"], margins=True);

In [ ]:
pd.crosstab( df["humidity"] , df["play"], margins=True);

In [ ]:
pd.crosstab( df["wind"] , df["play"], margins=True)

play    No  Yes  All
wind                
Strong   3    3    6
Weak     2    6    8
All      5    9   14

In [ ]:
# Encodage de la variable cible
from sklearn.preprocessing import LabelEncoder 
le1 = LabelEncoder()
target = le1.fit_transform(df["play"])
target

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [ ]:
# Encodage de la variable 
from sklearn.preprocessing import LabelEncoder 
le2 = LabelEncoder()
Outlook = le2.fit_transform(df["outlook"])
Outlook

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [ ]:
# Encodage de la variable 
from sklearn.preprocessing import LabelEncoder 
le3 = LabelEncoder()
Temp = le3.fit_transform(df["temp"])
Temp

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [ ]:
# Encodage de la variable 
from sklearn.preprocessing import LabelEncoder 
le4 = LabelEncoder()
Humidity = le4.fit_transform(df["humidity"])
Humidity

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0])

In [ ]:
# Encodage de la variable 
from sklearn.preprocessing import LabelEncoder 
le5 = LabelEncoder()
Wind = le5.fit_transform(df["wind"])
Wind

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [ ]:
# Y variable Cible + X variable explicatif = Apprentissage supervisé , Apprentissage non supervisé seulement avec variable X
y = target
x = pd.DataFrame( data = [ Outlook, Temp, Humidity, Wind ]  ).T
x.columns = ['outlook', 'temp', 'humidity', 'wind']
x

outlook  temp  humidity  wind
0         2     1         0     1
1         2     1         0     0
2         0     1         0     1
3         1     2         0     1
4         1     0         1     1
5         1     0         1     0
6         0     0         1     0
7         2     2         0     1
8         2     0         1     1
9         1     2         1     1
10        2     2         1     0
11        0     2         0     0
12        0     1         1     1
13        1     2         0     0

In [ ]:
# Echantillnage aléatoire (Random Simpling)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x,y, test_size=1/3, random_state=1)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(9, 4)
(5, 4)
(9,)
(5,)


In [ ]:
# Modélisation avec l'algorithme d'arbre de décision ( decision tree)
from sklearn.tree import DecisionTreeClassifier 
model = DecisionTreeClassifier(criterion='entropy')

In [ ]:
# Test
model.fit( x_train , y_train )

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
# Prédiction
y_pred = model.predict(x_test)
y_test == y_pred

array([False,  True, False,  True, False])

In [ ]:
# Evaluation
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test , y_pred )

array([[1, 0],
       [3, 1]])



```
- True positive 
- False positive
- False negative ( perte d'argent )
- True negative
```



In [ ]:
model.score(x_test,y_test)

0.4

In [ ]:
model.score(x_train,y_train)

1.0

In [ ]:
# Si le score de model train > score de model test 
# Overfitting : le model en train d'aprendre les données d'apprentissage